# @env dev

### Register user
POST {{apiUrl}}/v1/auth/register
Content-Type: application/json

{
  "name": "Nixon",
  "email": "nixon@gmail.com",
  "password": "nixon1981"
}

### Login user
POST {{apiUrl}}/v1/auth/login
Content-Type: application/json

{
  "email": "nixon@gmail.com",
  "password": "nixon1981"
}

###

### Save token from login response
@token = {{login.response.body.accessToken}}

### Refresh token
POST {{apiUrl}}/v1/auth/refresh
Content-Type: application/json

{}


### Logout user
POST {{apiUrl}}/v1/auth/logout
Content-Type: application/json

{}


### Me
GET {{apiUrl}}/v1/auth/me
Content-Type: application/json
Authorization: Bearer {{token}}
{}
