# @env dev

### Get all users
GET {{apiUrl}}/v1/users
Authorization: Bearer {{token}}
Accept: application/json


### Get post by id
GET {{apiUrl}}/v1/users/1

### Update a new user
PATCH {{apiUrl}}/v1/users/1
Content-Type: application/json

{
  "name": "Serii",
  "password": "serii2024"
}

### Delete a user by id
DELETE {{apiUrl}}/v1/users/3
