# @env dev

### Get all users
GET {{apiUrl}}/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJzZXJpaWJ1cmR1amFAZ21haWwuY29tIiwiaWF0IjoxNzY4NzY1Mzc1LCJleHAiOjE3Njg3NjYyNzV9.K4KV4R88NWwW-0hrh4T102xlTAp6OqPLuK3uEEkr5ps

### Get post by id
GET {{apiUrl}}/v1/users/1

### Update a new user
PATCH {{apiUrl}}/v1/users/1
Content-Type: application/json

{
  "name": "Serii",
  "password": "serii2024"
}

### Delete a user by id
DELETE {{apiUrl}}/v1/users/3
